// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2iyuAwpO-AskRELnU5SSpeVAaczbpAJE',
    appId: '1:986463954633:web:6fd9e7825d874288ee4f18',
    messagingSenderId: '986463954633',
    projectId: 'smarts-54b47',
    authDomain: 'smarts-54b47.firebaseapp.com',
    storageBucket: 'smarts-54b47.firebasestorage.app',
    measurementId: 'G-KMF771QLFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL8fVLqHgKB2kpdooJDJ7Ij03VL023OaI',
    appId: '1:986463954633:android:32304513ec161143ee4f18',
    messagingSenderId: '986463954633',
    projectId: 'smarts-54b47',
    storageBucket: 'smarts-54b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwFfEA--ShBA6yxjwqWBsqySpzM-FWTg',
    appId: '1:986463954633:ios:a3547ab2f8d5af81ee4f18',
    messagingSenderId: '986463954633',
    projectId: 'smarts-54b47',
    storageBucket: 'smarts-54b47.firebasestorage.app',
    iosBundleId: 'com.example.smarts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwFfEA--ShBA6yxjwqWBsqySpzM-FWTg',
    appId: '1:986463954633:ios:a3547ab2f8d5af81ee4f18',
    messagingSenderId: '986463954633',
    projectId: 'smarts-54b47',
    storageBucket: 'smarts-54b47.firebasestorage.app',
    iosBundleId: 'com.example.smarts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2iyuAwpO-AskRELnU5SSpeVAaczbpAJE',
    appId: '1:986463954633:web:9425d48054b5b95dee4f18',
    messagingSenderId: '986463954633',
    projectId: 'smarts-54b47',
    authDomain: 'smarts-54b47.firebaseapp.com',
    storageBucket: 'smarts-54b47.firebasestorage.app',
    measurementId: 'G-9RL6WF77DY',
  );
}
