platform :ios, '12.0' # (or keep '11.0' if needed)

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

disable_input_output_paths! if respond_to?(:disable_input_output_paths!)

# Dynamically set Flutter SDK path (Works Locally & on Codemagic)
flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path('..', File.dirname(__FILE__)) + '/flutter'

load File.join(flutter_root, 'packages/flutter_tools/bin/podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
